<main class="content-page">
  <div class="container">
    <div class="row">
      <div class="col-12 content">
        <h1>Privacy Policy</h1>
        <p>This Privacy Policy applies to all information collected via the website http://stocksdigital.com/.</p>
                
        <h5>How to contact us about privacy</h5>
        <p>Your privacy is very important to us (StocksDigital). For that reason, please read the following details carefully and get in contact with us if you have any questions. You can contact us here: <a href="mailto:webmaster@stocksdigital.com">webmaster@stocksdigital.com</a>.</p>
               
        <h5>Collection and Purpose</h5>
        <p>This website uses Google Analytics, a web analytics service provided by Google, Inc. (“Google”). Google Analytics uses “cookies”, which are text files stored on your computer, to help analyse site usage. The anonymous and non-personally identifiable information generated by the cookie about your use of this website is stored by Google. Google’s privacy policy can be found here: <a href="http://www.google.com/policies/privacy/" target="_blank">http://www.google.com/policies/privacy/</a>.</p>
        <p>This website also uses Google Analytics and/or AdWords cookies to advertise online through Google AdWords or third-party vendors to previous users of this website. For example, we might use the remarketing feature in Google AdWords to display ads on third-party websites to users who viewed certain pages, or who completed a certain action such as submitting a form on this website. This advertising allows us to reach users who previously visited our website, and to match the right users with the right message. You can opt out of Google’s use of cookies by visiting <a href="https://www.google.com/settings/u/0/ads/authenticated" target="_blank">Google’s Ads Settings</a>. Alternatively, you can opt out of a third-party vendor’s use of cookies by visiting the <a href="http://www.networkadvertising.org/choices/" target="_blank">Network Advertising Initiative opt-out page</a>.</p>
        <p>Most web browsers allow you to block all cookies, whilst some allow you to block only third-party cookies. Please check your browser settings and help documentation for more information. Please note that blocking all cookies may affect the usability of this and many websites.</p>
        <p>This website also records user data and personally identifiable information, such as your name and email address, in a CRM when you submit a form on this website to tie website sessions and engagement data to the same users. This allows us to get a more accurate user count in our analytics and reports, and to deliver better services to you. By using this website you agree to us using your data in this manner.</p>
        <p>StocksDigital may use Dashcord to monitor where website visitors click. The Dashcord Privacy Policy can be read here <a href="http://dashcord.com/pages/privacy-policy/" target="_blank">http://dashcord.com/pages/privacy-policy/</a>. If you wish to opt out you may set your browser to block all cookies, including Dashcord cookies. You may request that we remove any data we have collected about you. All of our emails include an unsubscribe link which allows you to opt out from receiving some or all types of electronic communication from us.</p>
        
        <h5>Disclosure</h5>
        <p>Except as stated above, your personal information will not be disclosed to any person or party not directly involved with us or this website without your consent.</p>
        
        <h5>Access and correction</h5>
        <p>National Privacy Principle 6 of the Australian Privacy Act allows you to get access to, and to correct any personal information that is held about you in certain circumstances. If you would like to obtain such access, please <a href="mailto:webmaster@stocksdigital.com">contact us</a>.</p>
        
        <h5>Your consent</h5>
        <p>By using this site, you consent to this website’s privacy policy. If there are any questions regarding this privacy policy you may <a href="mailto:webmaster@stocksdigital.com">contact us</a>.</p>
      </div>
    </div>
  </div>
</main>
